#%% [markdown]
# # Analysis 20190419
# * Written by: Chien-Cheng Shih
# * Running under conda env "lipidraft"
# * Source Images: testdata

#%%
# import resource
import subprocess
import os, sys
from core.fileop import DirCheck, ListFiles, GetPendingList, GetGrpFLs

#Functions ---------------------------------------------------------------
def dict2arg_fiji(arg):
    arg_str = str()
    for key, val in arg.items():
        str_tmp = str(key + '="' + val + '", ')
        arg_str = arg_str + str_tmp
    return arg_str

def list2arg_python(arg):
    arg_str = str()
    for var in arg:
        arg_str = arg_str +  "'" + str(var) + "' " 
    return arg_str
# -------------------------------------------------------------------------

#%% [markdown]
# ## Specify Parameters
# * `fiji`: path to the fiji application
# * `codepath`: the workspace for code/script
# * `datapath`: the workspace for STORM images and data
# * `analysis_dir`: the folder hosting data and images generated from this pipeline
#%%
fiji = '/Applications/Fiji.app/Contents/MacOS/ImageJ-macosx'
codepath = '/Users/michaelshih/Documents/code/wucci/storm_image_processing'
datapath = '/Volumes/LaCie_DataStorage/xiaochao_wei_STORM imaging/STORM_imaging'
analysis_dir = 'analysis_20190419'

#%% [markdown]
# ## Script name: `imgproc.py` 
# * env: ImageJ/Fiji
# * rewritten: 04/26/2019
# * verified 
# * output folder: `preprocessing`
# ### Output
#   1. `preproimg` (`.tif`): seperate the channels into individual folders 
#   2. `imgintensity` (`.csv`): return mean intensity for each time frame from the center of the image (128 pixel * 128 pixel)
#   3. `imginfo`:
#       1. `imgmetadata` (`.txt`): return the metadata
#       2. `imgstat.csv`: statistics from images
#           * image_name: the name of the image without extension
#           * ip_file_name: the name of the image with extension
#           * xSize: frame size on the x-axis
#           * ySize: frame size on the y-axis
#           * nSlices: frame size on the z-axis
#           * nFrames: number of time frames
#           * nChannels: number of channles
#           * size_MB: size of the file
#%%
script_name = 'imgproc.py'
ippath = '/Volumes/LaCie_DataStorage/xiaochao_wei_STORM imaging/STORM_imaging/resource/testdata'
opdir = 'preprocessing'
oppath = os.path.join(datapath, analysis_dir, opdir)

# create dict to store parameters
arg_dict = {
    'path': datapath,
    'dir_output': analysis_dir,
    'ippath': ippath,
    'outputdir': oppath,
    'batchmodeop': 'false',
}

arg = dict2arg_fiji(arg_dict)
print(arg)
#%%
# Run the script
#%%
subdir = 'Fiji'
scriptpath = os.path.join(codepath, subdir, script_name)
print("Start running: {}".format(script_name))
subprocess.check_output([fiji, '--ij2', '--run', arg])
print("End: {}".format(script_name))

#%% [markdown]
# ## Script name: `tstormanalysis.py` 
# * env: ImageJ/Fiji
# * plugin: [ThunderSTORM](https://github.com/zitmen/thunderstorm)
# * rewritten: 04/26/2019
# * verified 
# * output folder: `tstorm`
# ### Output generated by ThunderSTORM
#   1. `csvdata`: 
#       * (`.csv`): STORM dataset
#       * (`.txt`): protocol
#   2. `driftcorr` (`.json`): drift correction profile 
#   3. `histogram_plot` (`.tif`): histogram image with manification = 5.0
#%%
script_name = 'tstormanalysis.py'
ippath = '/Volumes/LaCie_DataStorage/xiaochao_wei_STORM imaging/STORM_imaging/analysis_20190419/preprocessing/preproimg'
opdir = 'preprocessing'
opsubdir = 'preproimg'

arg_dict = {
    'path': datapath,
    'dir_output': analysis_dir,
    'ippath': ippath,
    'batchmodeop': 'false', 
}
arg = dict2arg_fiji(arg_dict)
print(arg)

#%%
subdir = 'Fiji'
scriptpath = os.path.join(codepath, subdir, script_name)
print("Start running: {}".format(script_name))
subprocess.check_output([fiji, '--ij2', '--run', scriptpath, arg])
print("End: {}".format(script_name))

#%% [markdown]
# ## Script name: `csv_slicer.py` 
# * env: ImageJ/Fiji
# * rewritten: 04/26/2019
# * verified 
# * output folder: `csvdata_sliced`
# ### Output generated by ThunderSTORM
#   * `csvdata_sliced` (`.csv`): STORM data from T0 to T1
#%%
script_name = 'csv_slicer.py'
nchannel = 2
T0 = 5000
T1 = 10001
arg_list = [datapath, analysis_dir,'tstorm','csvdata', nchannel, T0, 10001, 'csvdata_sliced']
arg = list2arg_python(arg_list)
print(arg)

#%%
print("Start running: {}".format(script_name))
shellcmd = str('python '+ os.path.join(codepath, script_name)+ ' '+ arg)
print(shellcmd)
process = subprocess.run(shellcmd, shell = True, check=True)
print("End: {}".format(script_name))

#%%
# csv_slicer_crop.py
script_name = 'csv_slicer_crop.py'
arg_list = [datapath, analysis_dir,'tstorm','csvdata_sliced', 2, 3, 'csvdata_crop']
arg = list2arg_python(arg_list)
print(arg)

#%%
print("Start running: {}".format(script_name))
shellcmd = str('python '+ os.path.join(codepath, script_name)+ ' '+ arg)
print(shellcmd)
process = subprocess.run(shellcmd, shell = True, check=True)
print("End: {}".format(script_name))

#%%
# spatialanaylsis.R
script_name = 'spatialanaylsis.R'
arg_list = [datapath, analysis_dir,'tstorm','csvdata_crop', 2, 3, 'spacial_test', 'spacialdata', 'spacialdata_bi']
arg = list2arg_python(arg_list)
print(arg)

#%%
print("Start running: {}".format(script_name))
shellcmd = str('Rscript --vanilla '+ os.path.join(codepath, script_name)+ ' '+ arg)
print(shellcmd)
process = subprocess.run(shellcmd, shell = True, check=True)
print("End: {}".format(script_name))

#%%
# plot_spatialdata.py
script_name = 'plot_spatialdata.py'
arg_list = [datapath, analysis_dir,'spacial_test','spacialdata', 2, 'plot']
arg = list2arg_python(arg_list)
print(arg)

#%%
print("Start running: {}".format(script_name))
shellcmd = str('python '+ os.path.join(codepath, script_name)+ ' '+ arg)
print(shellcmd)
process = subprocess.run(shellcmd, shell = True, check=True)
print("End: {}".format(script_name))

